require('dotenv').config();
const express = require('express');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const winston = require('winston');
const DOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');
const { z } = require('zod');
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Constants
const PORT = process.env.PORT || 3001;
// ⚡ FIX 1: Switched to 1.5-flash for better free tier stability
const GEMINI_MODEL = 'gemini-2.5-flash'; 
const REQUEST_TIMEOUT = 60000; // Increased to 60s just in case
const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:3001';

// Validation schema
const enhanceRequestSchema = z.object({
  input: z.string().min(1).max(1000).trim(),
});

// Logger setup
const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.errors({ stack: true }),
    winston.format.json()
  ),
  transports: [
    new winston.transports.Console({
      format: winston.format.simple(),
    }),
  ],
});

// Environment validation
if (!process.env.GEMINI_API_KEY) {
  logger.error('GEMINI_API_KEY environment variable is required');
  process.exit(1);
}

// Initialize AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: GEMINI_MODEL });

// DOMPurify setup
const window = new JSDOM('').window;
const DOMPurifyInstance = DOMPurify(window);

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  message: 'Too many requests from this IP, please try again later.',
  standardHeaders: true,
  legacyHeaders: false,
});

const app = express();
const allowedOrigins = [
  'http://localhost:5173',
  'https://web-builder-mauve.vercel.app/'
];

// Middleware
app.use(cors({
  origin: true, // Allow all origins
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  credentials: true,
  optionsSuccessStatus: 200
}));

app.options('*', cors());
app.use(express.json({ limit: '10mb' }));
app.use(limiter);

// Timeout utility
const timeout = (ms) => new Promise((_, reject) =>
  setTimeout(() => reject(new Error('Request timeout')), ms)
);

// Health check
app.get('/health', (req, res) => {
  res.status(200).json({ status: 'OK', model: GEMINI_MODEL, timestamp: new Date().toISOString() });
});

// Main enhancement endpoint
app.post('/enhance', async (req, res) => {
  try {
    // 1. Validate input
    const { input } = enhanceRequestSchema.parse(req.body);

    // 2. Sanitize input
    const sanitizedInput = DOMPurifyInstance.sanitize(input);

    logger.info(`Processing Vibe Request for: "${sanitizedInput}"`);

    // ⚡ FIX 2: Unified "Master Prompt" (1 Request instead of 3) to save Quota
    const masterPrompt = `
      Act as an elite Product Development Team (Product Manager, CTO, and Lead Designer).
      Analyze the following web app idea: "${sanitizedInput}".

      Output the result in the following Markdown format exactly (do not add conversational text):

      # ⚡ Vibe Coder Blueprint

      ## 💡 Strategy & Concept
      * **Project Name:** [Creative Name]
      * **Value Proposition:** [One catchy sentence]
      * **Core Features:**
          * [Feature 1]
          * [Feature 2]
          * [Feature 3]

      ## 🛠 Tech Architecture
      * **Frontend:** [Frameworks]
      * **Backend:** [Languages/Frameworks]
      * **Database:** [Database choice]
      * **Deployment:** [Hosting service]

      ## 🎨 UI/UX Direction
      * **Vibe:** [e.g., Minimalist, Cyberpunk, Glassmorphism]
      * **Color Palette:** [Hex Code 1], [Hex Code 2], [Hex Code 3]
      * **Typography:** [Font recommendations]

      ---
      *Generated by Vibe Coder AI*
    `;

    // 3. Single AI Call (Quota Friendly)
    const result = await Promise.race([
      model.generateContent(masterPrompt),
      timeout(REQUEST_TIMEOUT)
    ]);

    const finalOutput = result.response.text();

    logger.info('Successfully enhanced idea');
    res.json({ enhanced: finalOutput });

  } catch (error) {
    logger.error('Enhancement error:', error);

    // Specific Error Handling
    if (error instanceof z.ZodError) {
      return res.status(400).json({
        error: 'Invalid input',
        details: error.errors
      });
    }

    if (error.message === 'Request timeout') {
      return res.status(408).json({
        enhanced: "⚠️ Request timed out. The AI is taking too long."
      });
    }

    // Handle Quota Error specifically - Return demo response
    if (error.status === 429 || error.message?.includes('429') || error.message?.includes('quota')) {
      logger.warn('API quota exceeded, returning demo response');
      const demoResponse = `# Portfolio Website for a Photographer

## 📋 Project Overview
Create a stunning portfolio website that showcases photographic work with elegant design and smooth user experience.

## 🛠️ Technical Stack
* **Frontend:** React with Next.js for optimal performance
* **Styling:** Tailwind CSS with custom animations
* **Backend:** Next.js API routes
* **Deployment:** Vercel for fast global delivery

## 🎨 UI/UX Direction
* **Vibe:** Minimalist, elegant, and professional
* **Color Palette:** #1a1a1a, #ffffff, #f3f4f6
* **Typography:** Playfair Display for headings, Inter for body text

## ✨ Key Features
* Hero section with featured photos
* Gallery with lightbox functionality
* About section with photographer's story
* Contact form with email integration
* Responsive design for all devices

---
*Demo response - API quota exceeded*`;

      return res.json({ enhanced: demoResponse });
    }

    res.status(500).json({
      enhanced: `# Demo Response - AI Service Unavailable

## 📋 What Your App Could Be
This is a demonstration of how Vibe Coder enhances your website ideas into detailed, actionable prompts.

## 🛠️ Sample Technical Stack
* **Frontend:** React/TypeScript with modern tooling
* **Styling:** Tailwind CSS for rapid development
* **Backend:** Node.js with Express
* **Database:** PostgreSQL with Prisma ORM

## 🎨 Design Direction
* **Vibe:** Clean, professional, and user-friendly
* **Colors:** Modern dark theme with accent colors
* **Typography:** System fonts for optimal performance

## ✨ Features to Consider
* Responsive design for all screen sizes
* Fast loading times and smooth animations
* Accessibility compliance
* SEO optimization

---
*Demo mode - Full functionality available when API is restored*`
    });
  }
});

// Graceful shutdown
const shutdown = () => {
  logger.info('Shutting down gracefully...');
  process.exit(0);
};

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

app.listen(PORT, () => {
  logger.info(`✅ Server running on http://localhost:${PORT}`);
});